import type { Category, Product, SiteSettings } from "@/lib/types";

const image = (id: string, alt: string) => {
  void alt;
  return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`;
};

export const demoSettings: SiteSettings = {
  brandName: "Hanabel Official",
  handle: "@hanabel.picks",
  bio: "Koleksi pilihan yang bikin rutinitas terasa lebih cantik, praktis, dan menyenangkan.",
  avatarUrl: image("photo-1494790108377-be9c29b29330", "Pemilik Hanabel"),
  coverUrl: image("photo-1515886657613-9f3515b0c78f", "Nuansa fashion lembut Hanabel"),
  disclosure:
    "Beberapa tautan di Hanabel adalah tautan affiliate. Harga dan ketersediaan mengikuti halaman Shopee.",
  socialLinks: [
    { label: "Instagram", href: "https://instagram.com/", icon: "instagram" },
    { label: "TikTok", href: "https://tiktok.com/", icon: "tiktok" },
    { label: "Threads", href: "https://threads.net/", icon: "threads" },
    { label: "Facebook", href: "https://facebook.com/", icon: "facebook" },
  ],
};

export const demoCategories: Category[] = [
  {
    id: "cat-fashion",
    slug: "fashion-style",
    name: "Fashion & Style",
    description: "Pilihan outfit dan aksesori untuk gaya sehari-hari.",
    iconKey: "dress",
    accentColor: "#f6d7ec",
    sortOrder: 1,
    status: "published",
    productCount: 3,
  },
  {
    id: "cat-beauty",
    slug: "kecantikan",
    name: "Kecantikan",
    description: "Temuan skincare dan beauty yang mudah masuk rutinitas.",
    iconKey: "beauty",
    accentColor: "#ffe0e9",
    sortOrder: 2,
    status: "published",
    productCount: 3,
  },
  {
    id: "cat-electronics",
    slug: "elektronik",
    name: "Elektronik",
    description: "Perangkat kecil yang membantu kerja dan aktivitas harian.",
    iconKey: "sparkles",
    accentColor: "#dfe5ff",
    sortOrder: 3,
    status: "published",
    productCount: 2,
  },
  {
    id: "cat-home",
    slug: "dekorasi-rumah",
    name: "Dekorasi Rumah",
    description: "Detail kecil untuk ruang yang terasa lebih personal.",
    iconKey: "home",
    accentColor: "#fff1d4",
    sortOrder: 4,
    status: "published",
    productCount: 2,
  },
  {
    id: "cat-wellness",
    slug: "olahraga-fitness",
    name: "Olahraga & Fitness",
    description: "Teman ringan untuk bergerak lebih konsisten.",
    iconKey: "activity",
    accentColor: "#d9f5e9",
    sortOrder: 5,
    status: "published",
    productCount: 2,
  },
];

const product = (
  values: Omit<Product, "images" | "createdAt" | "updatedAt"> & {
    imageId: string;
    imageAlt: string;
  },
): Product => ({
  ...values,
  images: [
    {
      id: `${values.id}-cover`,
      productId: values.id,
      storagePath: values.imageId,
      variant: "card",
      altText: values.imageAlt,
      sortOrder: 0,
      url: image(values.imageId, values.imageAlt),
    },
  ],
  createdAt: "2026-08-01T00:00:00.000Z",
  updatedAt: "2026-08-01T00:00:00.000Z",
});

export const demoProducts: Product[] = [
  product({
    id: "prod-001",
    categoryId: "cat-fashion",
    categorySlug: "fashion-style",
    categoryName: "Fashion & Style",
    name: "Tas bahu minimalis untuk daily look",
    slug: "tas-bahu-minimalis",
    shortDescription: "Siluet clean dengan ruang cukup untuk essentials.",
    description:
      "Pilihan tas yang mudah dipadukan untuk aktivitas harian, dari coffee run sampai agenda santai bersama teman.",
    highlights: ["Bentuk versatile", "Mudah dipadukan", "Cocok untuk daily use"],
    badge: "Pilihan",
    isFeatured: true,
    status: "published",
    affiliateUrl: "https://shopee.co.id/",
    imageId: "photo-1553062407-98eeb64c6a62",
    imageAlt: "Tas bahu warna cokelat di atas meja",
  }),
  product({
    id: "prod-002",
    categoryId: "cat-fashion",
    categorySlug: "fashion-style",
    categoryName: "Fashion & Style",
    name: "Kemeja linen relaxed",
    slug: "kemeja-linen-relaxed",
    shortDescription: "Layering ringan dengan tekstur yang tetap terlihat rapi.",
    description: "Kemeja santai untuk gaya effortless yang tetap terasa polished.",
    highlights: ["Ringan", "Warna mudah dipadukan", "Potongan relaxed"],
    badge: "Baru",
    isFeatured: true,
    status: "published",
    affiliateUrl: "https://shopee.co.id/",
    imageId: "photo-1596755389378-c31d21fd1273",
    imageAlt: "Kemeja linen putih tergantung",
  }),
  product({
    id: "prod-003",
    categoryId: "cat-fashion",
    categorySlug: "fashion-style",
    categoryName: "Fashion & Style",
    name: "Sandal strap nyaman",
    slug: "sandal-strap-nyaman",
    shortDescription: "Teman jalan santai dengan detail yang tidak berlebihan.",
    description: "Sandal praktis yang cocok untuk tampilan kasual sehari-hari.",
    highlights: ["Praktis", "Tampilan clean", "Mudah dipakai"],
    isFeatured: false,
    status: "published",
    affiliateUrl: "https://shopee.co.id/",
    imageId: "photo-1543163521-1bf539c55dd2",
    imageAlt: "Sandal fashion warna netral",
  }),
  product({
    id: "prod-004",
    categoryId: "cat-beauty",
    categorySlug: "kecantikan",
    categoryName: "Kecantikan",
    name: "Sunscreen ringan untuk daily",
    slug: "sunscreen-ringan-daily",
    shortDescription: "Tekstur nyaman untuk dipakai ulang sepanjang hari.",
    description: "Pilihan sunscreen harian dengan tekstur ringan dan mudah dilayer.",
    highlights: ["Tekstur ringan", "Nyaman untuk daily", "Mudah dilayer"],
    badge: "Favorit",
    isFeatured: true,
    status: "published",
    affiliateUrl: "https://shopee.co.id/",
    imageId: "photo-1556229010-6c3f2c9ca5f8",
    imageAlt: "Botol skincare di atas permukaan putih",
  }),
  product({
    id: "prod-005",
    categoryId: "cat-beauty",
    categorySlug: "kecantikan",
    categoryName: "Kecantikan",
    name: "Lip tint warna everyday",
    slug: "lip-tint-everyday",
    shortDescription: "Warna lembut yang mudah dipakai untuk tampilan segar.",
    description: "Lip tint untuk memberi warna natural tanpa membuat makeup terasa berat.",
    highlights: ["Warna natural", "Mudah dibaurkan", "Cocok untuk touch-up"],
    isFeatured: false,
    status: "published",
    affiliateUrl: "https://shopee.co.id/",
    imageId: "photo-1586495777744-4413f21062fa",
    imageAlt: "Lip tint merah muda",
  }),
  product({
    id: "prod-006",
    categoryId: "cat-beauty",
    categorySlug: "kecantikan",
    categoryName: "Kecantikan",
    name: "Hair claw minimal",
    slug: "hair-claw-minimal",
    shortDescription: "Aksesori rambut praktis dengan warna soft.",
    description: "Jepit rambut yang membantu styling cepat saat sedang terburu-buru.",
    highlights: ["Praktis", "Warna soft", "Mudah dibawa"],
    isFeatured: false,
    status: "published",
    affiliateUrl: "https://shopee.co.id/",
    imageId: "photo-1522337360788-8b13dee7a37e",
    imageAlt: "Aksesori rambut di atas meja",
  }),
  product({
    id: "prod-007",
    categoryId: "cat-electronics",
    categorySlug: "elektronik",
    categoryName: "Elektronik",
    name: "Lampu meja compact",
    slug: "lampu-meja-compact",
    shortDescription: "Penerangan kecil untuk meja kerja atau bedside.",
    description: "Lampu compact untuk membuat sudut kerja terasa lebih nyaman dan personal.",
    highlights: ["Hemat ruang", "Cocok untuk meja", "Nuansa hangat"],
    badge: "Baru",
    isFeatured: true,
    status: "published",
    affiliateUrl: "https://shopee.co.id/",
    imageId: "photo-1507473885765-e6ed057f782c",
    imageAlt: "Lampu meja menyala di ruangan gelap",
  }),
  product({
    id: "prod-008",
    categoryId: "cat-electronics",
    categorySlug: "elektronik",
    categoryName: "Elektronik",
    name: "Stand laptop adjustable",
    slug: "stand-laptop-adjustable",
    shortDescription: "Merapikan setup kerja dengan posisi yang lebih nyaman.",
    description: "Stand laptop untuk membantu meja kerja tetap rapi dan ergonomis.",
    highlights: ["Bisa diatur", "Setup lebih rapi", "Mudah dilipat"],
    isFeatured: false,
    status: "published",
    affiliateUrl: "https://shopee.co.id/",
    imageId: "photo-1496181133206-80ce9b88a853",
    imageAlt: "Laptop di atas meja kerja",
  }),
  product({
    id: "prod-009",
    categoryId: "cat-home",
    categorySlug: "dekorasi-rumah",
    categoryName: "Dekorasi Rumah",
    name: "Vas keramik mungil",
    slug: "vas-keramik-mungil",
    shortDescription: "Aksen kecil untuk rak, meja, atau sudut kosong.",
    description: "Vas mungil yang memberi detail hangat tanpa membuat ruangan penuh.",
    highlights: ["Aksen dekoratif", "Ukuran compact", "Warna netral"],
    badge: "Hits",
    isFeatured: true,
    status: "published",
    affiliateUrl: "https://shopee.co.id/",
    imageId: "photo-1610701596007-11502861dcfa",
    imageAlt: "Vas keramik putih dengan bunga kering",
  }),
  product({
    id: "prod-010",
    categoryId: "cat-home",
    categorySlug: "dekorasi-rumah",
    categoryName: "Dekorasi Rumah",
    name: "Cermin meja rounded",
    slug: "cermin-meja-rounded",
    shortDescription: "Bentuk lembut untuk meja rias atau entryway.",
    description: "Cermin meja dengan siluet rounded yang membuat area kecil terasa lebih selesai.",
    highlights: ["Siluet rounded", "Cocok untuk meja rias", "Mudah ditempatkan"],
    isFeatured: false,
    status: "published",
    affiliateUrl: "https://shopee.co.id/",
    imageId: "photo-1618220179428-22790b461013",
    imageAlt: "Cermin dekoratif di atas meja",
  }),
  product({
    id: "prod-011",
    categoryId: "cat-wellness",
    categorySlug: "olahraga-fitness",
    categoryName: "Olahraga & Fitness",
    name: "Yoga mat untuk pemula",
    slug: "yoga-mat-pemula",
    shortDescription: "Permukaan nyaman untuk mulai rutin bergerak.",
    description: "Yoga mat yang cocok untuk stretching, yoga ringan, atau home workout.",
    highlights: ["Nyaman dipakai", "Mudah digulung", "Cocok untuk pemula"],
    badge: "New",
    isFeatured: true,
    status: "published",
    affiliateUrl: "https://shopee.co.id/",
    imageId: "photo-1592432678016-e910b452f9a2",
    imageAlt: "Yoga mat warna lembut",
  }),
  product({
    id: "prod-012",
    categoryId: "cat-wellness",
    categorySlug: "olahraga-fitness",
    categoryName: "Olahraga & Fitness",
    name: "Tumbler daily ringan",
    slug: "tumbler-daily-ringan",
    shortDescription: "Membantu menjaga kebiasaan minum tetap praktis.",
    description: "Tumbler minimalis untuk dibawa ke kantor, kampus, atau saat bepergian.",
    highlights: ["Mudah dibawa", "Tampilan minimal", "Cocok untuk daily"],
    isFeatured: false,
    status: "published",
    affiliateUrl: "https://shopee.co.id/",
    imageId: "photo-1602143407151-7111542de6e8",
    imageAlt: "Tumbler stainless di atas meja",
  }),
];
