create extension if not exists pgcrypto;

create type public.content_status as enum ('draft', 'published', 'archived');

create table public.site_settings (
  id uuid primary key default gen_random_uuid(),
  brand_name text not null,
  handle text not null default '',
  bio text not null default '',
  avatar_url text not null default '',
  cover_url text not null default '',
  disclosure text not null default 'Beberapa tautan di Hanabel adalah tautan affiliate. Harga dan ketersediaan mengikuti Shopee.',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.social_links (
  id uuid primary key default gen_random_uuid(),
  label text not null,
  href text not null,
  icon text not null default 'link' check (icon in ('instagram', 'tiktok', 'facebook', 'threads', 'link')),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null,
  description text not null default '',
  icon_key text not null default 'sparkles',
  accent_color text not null default '#eee5ff',
  sort_order integer not null default 0,
  status public.content_status not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.categories(id) on delete restrict,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null,
  short_description text not null default '',
  description text not null default '',
  highlights jsonb not null default '[]'::jsonb,
  badge text,
  is_featured boolean not null default false,
  sort_order integer not null default 0,
  status public.content_status not null default 'draft',
  affiliate_url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  storage_path text not null,
  variant text not null default 'card' check (variant in ('thumbnail', 'card', 'detail', 'original')),
  alt_text text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (product_id, variant)
);

create table public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role = 'admin'),
  created_at timestamptz not null default now()
);

create table public.click_events (
  id bigint generated by default as identity primary key,
  product_id uuid references public.products(id) on delete set null,
  category_id uuid references public.categories(id) on delete set null,
  source text not null default 'direct',
  utm_source text,
  utm_medium text,
  utm_campaign text,
  referrer_host text,
  created_at timestamptz not null default now()
);

create index products_category_status_idx on public.products(category_id, status, sort_order);
create index products_featured_idx on public.products(is_featured, status, sort_order);
create index product_images_product_idx on public.product_images(product_id, sort_order);
create index click_events_created_idx on public.click_events(created_at desc);
create index click_events_product_idx on public.click_events(product_id, created_at desc);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_profiles
    where user_id = auth.uid() and role = 'admin'
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

alter table public.site_settings enable row level security;
alter table public.social_links enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.admin_profiles enable row level security;
alter table public.click_events enable row level security;

create policy "public can read site settings" on public.site_settings for select to anon, authenticated using (true);
create policy "admins manage site settings" on public.site_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "public can read active social links" on public.social_links for select to anon, authenticated using (is_active = true);
create policy "admins manage social links" on public.social_links for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "public can read published categories" on public.categories for select to anon, authenticated using (status = 'published');
create policy "admins manage categories" on public.categories for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "public can read published products" on public.products for select to anon, authenticated using (
  status = 'published' and exists (
    select 1 from public.categories c where c.id = category_id and c.status = 'published'
  )
);
create policy "admins manage products" on public.products for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "public can read published product images" on public.product_images for select to anon, authenticated using (
  exists (
    select 1 from public.products p
    join public.categories c on c.id = p.category_id
    where p.id = product_id and p.status = 'published' and c.status = 'published'
  )
);
create policy "admins manage product images" on public.product_images for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "admins can read admin profiles" on public.admin_profiles for select to authenticated using (public.is_admin() or user_id = auth.uid());
create policy "admins manage admin profiles" on public.admin_profiles for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "admins can read click events" on public.click_events for select to authenticated using (public.is_admin());

insert into storage.buckets (id, name, public)
values ('product-media', 'product-media', true)
on conflict (id) do nothing;

create policy "public can read product media" on storage.objects for select to public using (bucket_id = 'product-media');
create policy "admins can upload product media" on storage.objects for insert to authenticated with check (bucket_id = 'product-media' and public.is_admin());
create policy "admins can update product media" on storage.objects for update to authenticated using (bucket_id = 'product-media' and public.is_admin()) with check (bucket_id = 'product-media' and public.is_admin());
create policy "admins can delete product media" on storage.objects for delete to authenticated using (bucket_id = 'product-media' and public.is_admin());
